'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.431
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace AzureStorageBroker
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ServiceBusConfiguration", [Namespace]:="http://schemas.datacontract.org/2004/07/AzureClientInterface"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ServiceBusConfiguration
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IssuerField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NamespaceField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SecretField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Issuer() As String
            Get
                Return Me.IssuerField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IssuerField, value) <> true) Then
                    Me.IssuerField = value
                    Me.RaisePropertyChanged("Issuer")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property [Namespace]() As String
            Get
                Return Me.NamespaceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NamespaceField, value) <> true) Then
                    Me.NamespaceField = value
                    Me.RaisePropertyChanged("Namespace")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Secret() As String
            Get
                Return Me.SecretField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SecretField, value) <> true) Then
                    Me.SecretField = value
                    Me.RaisePropertyChanged("Secret")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="JobEntry", [Namespace]:="http://schemas.datacontract.org/2004/07/CloudDAL"),  _
     System.SerializableAttribute()>  _
    Partial Public Class JobEntry
        Inherits AzureStorageBroker.TableServiceEntity
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClientIdField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FinalImageUriField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FinishTimeField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RequestIdField As System.Guid
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SlicesField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SourceHeightField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SourceImageField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SourceImageUriField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SourceWidthField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StartTimeField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TileSizeField As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ClientId() As String
            Get
                Return Me.ClientIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClientIdField, value) <> true) Then
                    Me.ClientIdField = value
                    Me.RaisePropertyChanged("ClientId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FinalImageUri() As String
            Get
                Return Me.FinalImageUriField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FinalImageUriField, value) <> true) Then
                    Me.FinalImageUriField = value
                    Me.RaisePropertyChanged("FinalImageUri")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FinishTime() As Date
            Get
                Return Me.FinishTimeField
            End Get
            Set
                If (Me.FinishTimeField.Equals(value) <> true) Then
                    Me.FinishTimeField = value
                    Me.RaisePropertyChanged("FinishTime")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property RequestId() As System.Guid
            Get
                Return Me.RequestIdField
            End Get
            Set
                If (Me.RequestIdField.Equals(value) <> true) Then
                    Me.RequestIdField = value
                    Me.RaisePropertyChanged("RequestId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Slices() As Integer
            Get
                Return Me.SlicesField
            End Get
            Set
                If (Me.SlicesField.Equals(value) <> true) Then
                    Me.SlicesField = value
                    Me.RaisePropertyChanged("Slices")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SourceHeight() As Integer
            Get
                Return Me.SourceHeightField
            End Get
            Set
                If (Me.SourceHeightField.Equals(value) <> true) Then
                    Me.SourceHeightField = value
                    Me.RaisePropertyChanged("SourceHeight")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SourceImage() As String
            Get
                Return Me.SourceImageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SourceImageField, value) <> true) Then
                    Me.SourceImageField = value
                    Me.RaisePropertyChanged("SourceImage")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SourceImageUri() As String
            Get
                Return Me.SourceImageUriField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SourceImageUriField, value) <> true) Then
                    Me.SourceImageUriField = value
                    Me.RaisePropertyChanged("SourceImageUri")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SourceWidth() As Integer
            Get
                Return Me.SourceWidthField
            End Get
            Set
                If (Me.SourceWidthField.Equals(value) <> true) Then
                    Me.SourceWidthField = value
                    Me.RaisePropertyChanged("SourceWidth")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StartTime() As Date
            Get
                Return Me.StartTimeField
            End Get
            Set
                If (Me.StartTimeField.Equals(value) <> true) Then
                    Me.StartTimeField = value
                    Me.RaisePropertyChanged("StartTime")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TileSize() As Integer
            Get
                Return Me.TileSizeField
            End Get
            Set
                If (Me.TileSizeField.Equals(value) <> true) Then
                    Me.TileSizeField = value
                    Me.RaisePropertyChanged("TileSize")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="TableServiceEntity", [Namespace]:="http://schemas.datacontract.org/2004/07/Microsoft.WindowsAzure.StorageClient"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(AzureStorageBroker.StatusEntry)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(AzureStorageBroker.JobEntry))>  _
    Partial Public Class TableServiceEntity
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PartitionKeyField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RowKeyField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TimestampField As Date
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PartitionKey() As String
            Get
                Return Me.PartitionKeyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PartitionKeyField, value) <> true) Then
                    Me.PartitionKeyField = value
                    Me.RaisePropertyChanged("PartitionKey")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property RowKey() As String
            Get
                Return Me.RowKeyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RowKeyField, value) <> true) Then
                    Me.RowKeyField = value
                    Me.RaisePropertyChanged("RowKey")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Timestamp() As Date
            Get
                Return Me.TimestampField
            End Get
            Set
                If (Me.TimestampField.Equals(value) <> true) Then
                    Me.TimestampField = value
                    Me.RaisePropertyChanged("Timestamp")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="StatusEntry", [Namespace]:="http://schemas.datacontract.org/2004/07/CloudDAL"),  _
     System.SerializableAttribute()>  _
    Partial Public Class StatusEntry
        Inherits AzureStorageBroker.TableServiceEntity
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MessageField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RequestIdField As System.Guid
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RoleIdField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Message() As String
            Get
                Return Me.MessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MessageField, value) <> true) Then
                    Me.MessageField = value
                    Me.RaisePropertyChanged("Message")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property RequestId() As System.Guid
            Get
                Return Me.RequestIdField
            End Get
            Set
                If (Me.RequestIdField.Equals(value) <> true) Then
                    Me.RequestIdField = value
                    Me.RaisePropertyChanged("RequestId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property RoleId() As String
            Get
                Return Me.RoleIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RoleIdField, value) <> true) Then
                    Me.RoleIdField = value
                    Me.RaisePropertyChanged("RoleId")
                End If
            End Set
        End Property
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="AzureStorageBroker.IStorageBroker")>  _
    Public Interface IStorageBroker
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IStorageBroker/EnumerateImageLibraries", ReplyAction:="http://tempuri.org/IStorageBroker/EnumerateImageLibrariesResponse")>  _
        Function EnumerateImageLibraries(ByVal clientRegistrationId As String) As System.Collections.Generic.List(Of System.Collections.Generic.KeyValuePair(Of System.Uri, String))
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/IStorageBroker/EnumerateImageLibraries", ReplyAction:="http://tempuri.org/IStorageBroker/EnumerateImageLibrariesResponse")>  _
        Function BeginEnumerateImageLibraries(ByVal clientRegistrationId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndEnumerateImageLibraries(ByVal result As System.IAsyncResult) As System.Collections.Generic.List(Of System.Collections.Generic.KeyValuePair(Of System.Uri, String))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IStorageBroker/EnumerateImages", ReplyAction:="http://tempuri.org/IStorageBroker/EnumerateImagesResponse")>  _
        Function EnumerateImages(ByVal container As System.Uri) As System.Collections.Generic.List(Of String)
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/IStorageBroker/EnumerateImages", ReplyAction:="http://tempuri.org/IStorageBroker/EnumerateImagesResponse")>  _
        Function BeginEnumerateImages(ByVal container As System.Uri, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndEnumerateImages(ByVal result As System.IAsyncResult) As System.Collections.Generic.List(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IStorageBroker/GetServiceBusConfiguration", ReplyAction:="http://tempuri.org/IStorageBroker/GetServiceBusConfigurationResponse")>  _
        Function GetServiceBusConfiguration(ByVal clientRegistrationId As String) As AzureStorageBroker.ServiceBusConfiguration
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/IStorageBroker/GetServiceBusConfiguration", ReplyAction:="http://tempuri.org/IStorageBroker/GetServiceBusConfigurationResponse")>  _
        Function BeginGetServiceBusConfiguration(ByVal clientRegistrationId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndGetServiceBusConfiguration(ByVal result As System.IAsyncResult) As AzureStorageBroker.ServiceBusConfiguration
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IStorageBroker/GetJobsForClient", ReplyAction:="http://tempuri.org/IStorageBroker/GetJobsForClientResponse")>  _
        Function GetJobsForClient(ByVal clientRegistrationId As String) As System.Collections.Generic.List(Of AzureStorageBroker.JobEntry)
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/IStorageBroker/GetJobsForClient", ReplyAction:="http://tempuri.org/IStorageBroker/GetJobsForClientResponse")>  _
        Function BeginGetJobsForClient(ByVal clientRegistrationId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndGetJobsForClient(ByVal result As System.IAsyncResult) As System.Collections.Generic.List(Of AzureStorageBroker.JobEntry)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IStorageBroker/GetStatusEntriesForJob", ReplyAction:="http://tempuri.org/IStorageBroker/GetStatusEntriesForJobResponse")>  _
        Function GetStatusEntriesForJob(ByVal clientRegistrationId As String, ByVal jobId As System.Guid) As System.Collections.Generic.List(Of AzureStorageBroker.StatusEntry)
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/IStorageBroker/GetStatusEntriesForJob", ReplyAction:="http://tempuri.org/IStorageBroker/GetStatusEntriesForJobResponse")>  _
        Function BeginGetStatusEntriesForJob(ByVal clientRegistrationId As String, ByVal jobId As System.Guid, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndGetStatusEntriesForJob(ByVal result As System.IAsyncResult) As System.Collections.Generic.List(Of AzureStorageBroker.StatusEntry)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IStorageBrokerChannel
        Inherits AzureStorageBroker.IStorageBroker, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class EnumerateImageLibrariesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As System.Collections.Generic.List(Of System.Collections.Generic.KeyValuePair(Of System.Uri, String))
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Collections.Generic.List(Of System.Collections.Generic.KeyValuePair(Of System.Uri, String)))
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class EnumerateImagesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As System.Collections.Generic.List(Of String)
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Collections.Generic.List(Of String))
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class GetServiceBusConfigurationCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As AzureStorageBroker.ServiceBusConfiguration
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),AzureStorageBroker.ServiceBusConfiguration)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class GetJobsForClientCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As System.Collections.Generic.List(Of AzureStorageBroker.JobEntry)
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Collections.Generic.List(Of AzureStorageBroker.JobEntry))
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class GetStatusEntriesForJobCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As System.Collections.Generic.List(Of AzureStorageBroker.StatusEntry)
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Collections.Generic.List(Of AzureStorageBroker.StatusEntry))
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class StorageBrokerClient
        Inherits System.ServiceModel.ClientBase(Of AzureStorageBroker.IStorageBroker)
        Implements AzureStorageBroker.IStorageBroker
        
        Private onBeginEnumerateImageLibrariesDelegate As BeginOperationDelegate
        
        Private onEndEnumerateImageLibrariesDelegate As EndOperationDelegate
        
        Private onEnumerateImageLibrariesCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginEnumerateImagesDelegate As BeginOperationDelegate
        
        Private onEndEnumerateImagesDelegate As EndOperationDelegate
        
        Private onEnumerateImagesCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginGetServiceBusConfigurationDelegate As BeginOperationDelegate
        
        Private onEndGetServiceBusConfigurationDelegate As EndOperationDelegate
        
        Private onGetServiceBusConfigurationCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginGetJobsForClientDelegate As BeginOperationDelegate
        
        Private onEndGetJobsForClientDelegate As EndOperationDelegate
        
        Private onGetJobsForClientCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginGetStatusEntriesForJobDelegate As BeginOperationDelegate
        
        Private onEndGetStatusEntriesForJobDelegate As EndOperationDelegate
        
        Private onGetStatusEntriesForJobCompletedDelegate As System.Threading.SendOrPostCallback
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Event EnumerateImageLibrariesCompleted As System.EventHandler(Of EnumerateImageLibrariesCompletedEventArgs)
        
        Public Event EnumerateImagesCompleted As System.EventHandler(Of EnumerateImagesCompletedEventArgs)
        
        Public Event GetServiceBusConfigurationCompleted As System.EventHandler(Of GetServiceBusConfigurationCompletedEventArgs)
        
        Public Event GetJobsForClientCompleted As System.EventHandler(Of GetJobsForClientCompletedEventArgs)
        
        Public Event GetStatusEntriesForJobCompleted As System.EventHandler(Of GetStatusEntriesForJobCompletedEventArgs)
        
        Public Function EnumerateImageLibraries(ByVal clientRegistrationId As String) As System.Collections.Generic.List(Of System.Collections.Generic.KeyValuePair(Of System.Uri, String)) Implements AzureStorageBroker.IStorageBroker.EnumerateImageLibraries
            Return MyBase.Channel.EnumerateImageLibraries(clientRegistrationId)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginEnumerateImageLibraries(ByVal clientRegistrationId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements AzureStorageBroker.IStorageBroker.BeginEnumerateImageLibraries
            Return MyBase.Channel.BeginEnumerateImageLibraries(clientRegistrationId, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndEnumerateImageLibraries(ByVal result As System.IAsyncResult) As System.Collections.Generic.List(Of System.Collections.Generic.KeyValuePair(Of System.Uri, String)) Implements AzureStorageBroker.IStorageBroker.EndEnumerateImageLibraries
            Return MyBase.Channel.EndEnumerateImageLibraries(result)
        End Function
        
        Private Function OnBeginEnumerateImageLibraries(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim clientRegistrationId As String = CType(inValues(0),String)
            Return Me.BeginEnumerateImageLibraries(clientRegistrationId, callback, asyncState)
        End Function
        
        Private Function OnEndEnumerateImageLibraries(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As System.Collections.Generic.List(Of System.Collections.Generic.KeyValuePair(Of System.Uri, String)) = Me.EndEnumerateImageLibraries(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnEnumerateImageLibrariesCompleted(ByVal state As Object)
            If (Not (Me.EnumerateImageLibrariesCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent EnumerateImageLibrariesCompleted(Me, New EnumerateImageLibrariesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub EnumerateImageLibrariesAsync(ByVal clientRegistrationId As String)
            Me.EnumerateImageLibrariesAsync(clientRegistrationId, Nothing)
        End Sub
        
        Public Overloads Sub EnumerateImageLibrariesAsync(ByVal clientRegistrationId As String, ByVal userState As Object)
            If (Me.onBeginEnumerateImageLibrariesDelegate Is Nothing) Then
                Me.onBeginEnumerateImageLibrariesDelegate = AddressOf Me.OnBeginEnumerateImageLibraries
            End If
            If (Me.onEndEnumerateImageLibrariesDelegate Is Nothing) Then
                Me.onEndEnumerateImageLibrariesDelegate = AddressOf Me.OnEndEnumerateImageLibraries
            End If
            If (Me.onEnumerateImageLibrariesCompletedDelegate Is Nothing) Then
                Me.onEnumerateImageLibrariesCompletedDelegate = AddressOf Me.OnEnumerateImageLibrariesCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginEnumerateImageLibrariesDelegate, New Object() {clientRegistrationId}, Me.onEndEnumerateImageLibrariesDelegate, Me.onEnumerateImageLibrariesCompletedDelegate, userState)
        End Sub
        
        Public Function EnumerateImages(ByVal container As System.Uri) As System.Collections.Generic.List(Of String) Implements AzureStorageBroker.IStorageBroker.EnumerateImages
            Return MyBase.Channel.EnumerateImages(container)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginEnumerateImages(ByVal container As System.Uri, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements AzureStorageBroker.IStorageBroker.BeginEnumerateImages
            Return MyBase.Channel.BeginEnumerateImages(container, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndEnumerateImages(ByVal result As System.IAsyncResult) As System.Collections.Generic.List(Of String) Implements AzureStorageBroker.IStorageBroker.EndEnumerateImages
            Return MyBase.Channel.EndEnumerateImages(result)
        End Function
        
        Private Function OnBeginEnumerateImages(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim container As System.Uri = CType(inValues(0),System.Uri)
            Return Me.BeginEnumerateImages(container, callback, asyncState)
        End Function
        
        Private Function OnEndEnumerateImages(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As System.Collections.Generic.List(Of String) = Me.EndEnumerateImages(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnEnumerateImagesCompleted(ByVal state As Object)
            If (Not (Me.EnumerateImagesCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent EnumerateImagesCompleted(Me, New EnumerateImagesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub EnumerateImagesAsync(ByVal container As System.Uri)
            Me.EnumerateImagesAsync(container, Nothing)
        End Sub
        
        Public Overloads Sub EnumerateImagesAsync(ByVal container As System.Uri, ByVal userState As Object)
            If (Me.onBeginEnumerateImagesDelegate Is Nothing) Then
                Me.onBeginEnumerateImagesDelegate = AddressOf Me.OnBeginEnumerateImages
            End If
            If (Me.onEndEnumerateImagesDelegate Is Nothing) Then
                Me.onEndEnumerateImagesDelegate = AddressOf Me.OnEndEnumerateImages
            End If
            If (Me.onEnumerateImagesCompletedDelegate Is Nothing) Then
                Me.onEnumerateImagesCompletedDelegate = AddressOf Me.OnEnumerateImagesCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginEnumerateImagesDelegate, New Object() {container}, Me.onEndEnumerateImagesDelegate, Me.onEnumerateImagesCompletedDelegate, userState)
        End Sub
        
        Public Function GetServiceBusConfiguration(ByVal clientRegistrationId As String) As AzureStorageBroker.ServiceBusConfiguration Implements AzureStorageBroker.IStorageBroker.GetServiceBusConfiguration
            Return MyBase.Channel.GetServiceBusConfiguration(clientRegistrationId)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginGetServiceBusConfiguration(ByVal clientRegistrationId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements AzureStorageBroker.IStorageBroker.BeginGetServiceBusConfiguration
            Return MyBase.Channel.BeginGetServiceBusConfiguration(clientRegistrationId, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndGetServiceBusConfiguration(ByVal result As System.IAsyncResult) As AzureStorageBroker.ServiceBusConfiguration Implements AzureStorageBroker.IStorageBroker.EndGetServiceBusConfiguration
            Return MyBase.Channel.EndGetServiceBusConfiguration(result)
        End Function
        
        Private Function OnBeginGetServiceBusConfiguration(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim clientRegistrationId As String = CType(inValues(0),String)
            Return Me.BeginGetServiceBusConfiguration(clientRegistrationId, callback, asyncState)
        End Function
        
        Private Function OnEndGetServiceBusConfiguration(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As AzureStorageBroker.ServiceBusConfiguration = Me.EndGetServiceBusConfiguration(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnGetServiceBusConfigurationCompleted(ByVal state As Object)
            If (Not (Me.GetServiceBusConfigurationCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent GetServiceBusConfigurationCompleted(Me, New GetServiceBusConfigurationCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub GetServiceBusConfigurationAsync(ByVal clientRegistrationId As String)
            Me.GetServiceBusConfigurationAsync(clientRegistrationId, Nothing)
        End Sub
        
        Public Overloads Sub GetServiceBusConfigurationAsync(ByVal clientRegistrationId As String, ByVal userState As Object)
            If (Me.onBeginGetServiceBusConfigurationDelegate Is Nothing) Then
                Me.onBeginGetServiceBusConfigurationDelegate = AddressOf Me.OnBeginGetServiceBusConfiguration
            End If
            If (Me.onEndGetServiceBusConfigurationDelegate Is Nothing) Then
                Me.onEndGetServiceBusConfigurationDelegate = AddressOf Me.OnEndGetServiceBusConfiguration
            End If
            If (Me.onGetServiceBusConfigurationCompletedDelegate Is Nothing) Then
                Me.onGetServiceBusConfigurationCompletedDelegate = AddressOf Me.OnGetServiceBusConfigurationCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginGetServiceBusConfigurationDelegate, New Object() {clientRegistrationId}, Me.onEndGetServiceBusConfigurationDelegate, Me.onGetServiceBusConfigurationCompletedDelegate, userState)
        End Sub
        
        Public Function GetJobsForClient(ByVal clientRegistrationId As String) As System.Collections.Generic.List(Of AzureStorageBroker.JobEntry) Implements AzureStorageBroker.IStorageBroker.GetJobsForClient
            Return MyBase.Channel.GetJobsForClient(clientRegistrationId)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginGetJobsForClient(ByVal clientRegistrationId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements AzureStorageBroker.IStorageBroker.BeginGetJobsForClient
            Return MyBase.Channel.BeginGetJobsForClient(clientRegistrationId, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndGetJobsForClient(ByVal result As System.IAsyncResult) As System.Collections.Generic.List(Of AzureStorageBroker.JobEntry) Implements AzureStorageBroker.IStorageBroker.EndGetJobsForClient
            Return MyBase.Channel.EndGetJobsForClient(result)
        End Function
        
        Private Function OnBeginGetJobsForClient(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim clientRegistrationId As String = CType(inValues(0),String)
            Return Me.BeginGetJobsForClient(clientRegistrationId, callback, asyncState)
        End Function
        
        Private Function OnEndGetJobsForClient(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As System.Collections.Generic.List(Of AzureStorageBroker.JobEntry) = Me.EndGetJobsForClient(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnGetJobsForClientCompleted(ByVal state As Object)
            If (Not (Me.GetJobsForClientCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent GetJobsForClientCompleted(Me, New GetJobsForClientCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub GetJobsForClientAsync(ByVal clientRegistrationId As String)
            Me.GetJobsForClientAsync(clientRegistrationId, Nothing)
        End Sub
        
        Public Overloads Sub GetJobsForClientAsync(ByVal clientRegistrationId As String, ByVal userState As Object)
            If (Me.onBeginGetJobsForClientDelegate Is Nothing) Then
                Me.onBeginGetJobsForClientDelegate = AddressOf Me.OnBeginGetJobsForClient
            End If
            If (Me.onEndGetJobsForClientDelegate Is Nothing) Then
                Me.onEndGetJobsForClientDelegate = AddressOf Me.OnEndGetJobsForClient
            End If
            If (Me.onGetJobsForClientCompletedDelegate Is Nothing) Then
                Me.onGetJobsForClientCompletedDelegate = AddressOf Me.OnGetJobsForClientCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginGetJobsForClientDelegate, New Object() {clientRegistrationId}, Me.onEndGetJobsForClientDelegate, Me.onGetJobsForClientCompletedDelegate, userState)
        End Sub
        
        Public Function GetStatusEntriesForJob(ByVal clientRegistrationId As String, ByVal jobId As System.Guid) As System.Collections.Generic.List(Of AzureStorageBroker.StatusEntry) Implements AzureStorageBroker.IStorageBroker.GetStatusEntriesForJob
            Return MyBase.Channel.GetStatusEntriesForJob(clientRegistrationId, jobId)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginGetStatusEntriesForJob(ByVal clientRegistrationId As String, ByVal jobId As System.Guid, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements AzureStorageBroker.IStorageBroker.BeginGetStatusEntriesForJob
            Return MyBase.Channel.BeginGetStatusEntriesForJob(clientRegistrationId, jobId, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndGetStatusEntriesForJob(ByVal result As System.IAsyncResult) As System.Collections.Generic.List(Of AzureStorageBroker.StatusEntry) Implements AzureStorageBroker.IStorageBroker.EndGetStatusEntriesForJob
            Return MyBase.Channel.EndGetStatusEntriesForJob(result)
        End Function
        
        Private Function OnBeginGetStatusEntriesForJob(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim clientRegistrationId As String = CType(inValues(0),String)
            Dim jobId As System.Guid = CType(inValues(1),System.Guid)
            Return Me.BeginGetStatusEntriesForJob(clientRegistrationId, jobId, callback, asyncState)
        End Function
        
        Private Function OnEndGetStatusEntriesForJob(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As System.Collections.Generic.List(Of AzureStorageBroker.StatusEntry) = Me.EndGetStatusEntriesForJob(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnGetStatusEntriesForJobCompleted(ByVal state As Object)
            If (Not (Me.GetStatusEntriesForJobCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent GetStatusEntriesForJobCompleted(Me, New GetStatusEntriesForJobCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub GetStatusEntriesForJobAsync(ByVal clientRegistrationId As String, ByVal jobId As System.Guid)
            Me.GetStatusEntriesForJobAsync(clientRegistrationId, jobId, Nothing)
        End Sub
        
        Public Overloads Sub GetStatusEntriesForJobAsync(ByVal clientRegistrationId As String, ByVal jobId As System.Guid, ByVal userState As Object)
            If (Me.onBeginGetStatusEntriesForJobDelegate Is Nothing) Then
                Me.onBeginGetStatusEntriesForJobDelegate = AddressOf Me.OnBeginGetStatusEntriesForJob
            End If
            If (Me.onEndGetStatusEntriesForJobDelegate Is Nothing) Then
                Me.onEndGetStatusEntriesForJobDelegate = AddressOf Me.OnEndGetStatusEntriesForJob
            End If
            If (Me.onGetStatusEntriesForJobCompletedDelegate Is Nothing) Then
                Me.onGetStatusEntriesForJobCompletedDelegate = AddressOf Me.OnGetStatusEntriesForJobCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginGetStatusEntriesForJobDelegate, New Object() {clientRegistrationId, jobId}, Me.onEndGetStatusEntriesForJobDelegate, Me.onGetStatusEntriesForJobCompletedDelegate, userState)
        End Sub
    End Class
End Namespace
