'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.431
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace AzureJobBroker
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="AzureJobBroker.IJobBroker")>  _
    Public Interface IJobBroker
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IJobBroker/SubmitImageForProcessing", ReplyAction:="http://tempuri.org/IJobBroker/SubmitImageForProcessingResponse")>  _
        Sub SubmitImageForProcessing(ByVal clientId As String, ByVal requestId As System.Guid, ByVal imageLibraryUri As System.Uri, ByVal originalLocation As String, ByVal tileSize As Byte, ByVal slices As Byte, ByVal imgBytes() As Byte)
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/IJobBroker/SubmitImageForProcessing", ReplyAction:="http://tempuri.org/IJobBroker/SubmitImageForProcessingResponse")>  _
        Function BeginSubmitImageForProcessing(ByVal clientId As String, ByVal requestId As System.Guid, ByVal imageLibraryUri As System.Uri, ByVal originalLocation As String, ByVal tileSize As Byte, ByVal slices As Byte, ByVal imgBytes() As Byte, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Sub EndSubmitImageForProcessing(ByVal result As System.IAsyncResult)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IJobBrokerChannel
        Inherits AzureJobBroker.IJobBroker, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class JobBrokerClient
        Inherits System.ServiceModel.ClientBase(Of AzureJobBroker.IJobBroker)
        Implements AzureJobBroker.IJobBroker
        
        Private onBeginSubmitImageForProcessingDelegate As BeginOperationDelegate
        
        Private onEndSubmitImageForProcessingDelegate As EndOperationDelegate
        
        Private onSubmitImageForProcessingCompletedDelegate As System.Threading.SendOrPostCallback
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Event SubmitImageForProcessingCompleted As System.EventHandler(Of System.ComponentModel.AsyncCompletedEventArgs)
        
        Public Sub SubmitImageForProcessing(ByVal clientId As String, ByVal requestId As System.Guid, ByVal imageLibraryUri As System.Uri, ByVal originalLocation As String, ByVal tileSize As Byte, ByVal slices As Byte, ByVal imgBytes() As Byte) Implements AzureJobBroker.IJobBroker.SubmitImageForProcessing
            MyBase.Channel.SubmitImageForProcessing(clientId, requestId, imageLibraryUri, originalLocation, tileSize, slices, imgBytes)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginSubmitImageForProcessing(ByVal clientId As String, ByVal requestId As System.Guid, ByVal imageLibraryUri As System.Uri, ByVal originalLocation As String, ByVal tileSize As Byte, ByVal slices As Byte, ByVal imgBytes() As Byte, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements AzureJobBroker.IJobBroker.BeginSubmitImageForProcessing
            Return MyBase.Channel.BeginSubmitImageForProcessing(clientId, requestId, imageLibraryUri, originalLocation, tileSize, slices, imgBytes, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Sub EndSubmitImageForProcessing(ByVal result As System.IAsyncResult) Implements AzureJobBroker.IJobBroker.EndSubmitImageForProcessing
            MyBase.Channel.EndSubmitImageForProcessing(result)
        End Sub
        
        Private Function OnBeginSubmitImageForProcessing(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim clientId As String = CType(inValues(0),String)
            Dim requestId As System.Guid = CType(inValues(1),System.Guid)
            Dim imageLibraryUri As System.Uri = CType(inValues(2),System.Uri)
            Dim originalLocation As String = CType(inValues(3),String)
            Dim tileSize As Byte = CType(inValues(4),Byte)
            Dim slices As Byte = CType(inValues(5),Byte)
            Dim imgBytes() As Byte = CType(inValues(6),Byte())
            Return Me.BeginSubmitImageForProcessing(clientId, requestId, imageLibraryUri, originalLocation, tileSize, slices, imgBytes, callback, asyncState)
        End Function
        
        Private Function OnEndSubmitImageForProcessing(ByVal result As System.IAsyncResult) As Object()
            Me.EndSubmitImageForProcessing(result)
            Return Nothing
        End Function
        
        Private Sub OnSubmitImageForProcessingCompleted(ByVal state As Object)
            If (Not (Me.SubmitImageForProcessingCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent SubmitImageForProcessingCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub SubmitImageForProcessingAsync(ByVal clientId As String, ByVal requestId As System.Guid, ByVal imageLibraryUri As System.Uri, ByVal originalLocation As String, ByVal tileSize As Byte, ByVal slices As Byte, ByVal imgBytes() As Byte)
            Me.SubmitImageForProcessingAsync(clientId, requestId, imageLibraryUri, originalLocation, tileSize, slices, imgBytes, Nothing)
        End Sub
        
        Public Overloads Sub SubmitImageForProcessingAsync(ByVal clientId As String, ByVal requestId As System.Guid, ByVal imageLibraryUri As System.Uri, ByVal originalLocation As String, ByVal tileSize As Byte, ByVal slices As Byte, ByVal imgBytes() As Byte, ByVal userState As Object)
            If (Me.onBeginSubmitImageForProcessingDelegate Is Nothing) Then
                Me.onBeginSubmitImageForProcessingDelegate = AddressOf Me.OnBeginSubmitImageForProcessing
            End If
            If (Me.onEndSubmitImageForProcessingDelegate Is Nothing) Then
                Me.onEndSubmitImageForProcessingDelegate = AddressOf Me.OnEndSubmitImageForProcessing
            End If
            If (Me.onSubmitImageForProcessingCompletedDelegate Is Nothing) Then
                Me.onSubmitImageForProcessingCompletedDelegate = AddressOf Me.OnSubmitImageForProcessingCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginSubmitImageForProcessingDelegate, New Object() {clientId, requestId, imageLibraryUri, originalLocation, tileSize, slices, imgBytes}, Me.onEndSubmitImageForProcessingDelegate, Me.onSubmitImageForProcessingCompletedDelegate, userState)
        End Sub
    End Class
End Namespace
